# Thanks to https://raw.githubusercontent.com/jenkinsci/.github/master/.github/release-drafter.yml
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '💥️ Breaking changes'
    labels:
      - 'breaking :collision:'
  - title: '🚨 Removed'
    label: 'removed :exclamation:'
  - title: '🚀 New features and improvements'
    labels:
      - 'enhancement :muscle:'
      - 'feature :art:'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug :grin:'
      - 'security :woman_technologist:'
      - 'regression :leftwards_arrow_with_hook:'
   # Default label used by Dependabot
  - title: '📝 Documentation updates'
    label: 'documentation :u6e80:'
  - title: '👻 Maintenance'
    labels: 'internal :carousel_horse:'
  - title: '🚦 Tests'
    labels: 'test :mag:'

exclude-labels:
  - 'dependencies :arrow_up:'
  - 'no-changelog'
  - 'skip-changelog'

template: |
  ## What’s Changed

  $CHANGES
