# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
      - "obernardovieira"
    ignored_updates:
      - match:
          dependency_name: "jest"
          dependency_name: "web3"
